# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 50) do

  create_table "divisions", :force => true do |t|
    t.column "name",       :string,   :limit => 200, :default => "", :null => false
    t.column "parent_id",  :integer
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "drecom_users", :force => true do |t|
    t.column "email",      :string,   :limit => 256, :default => "", :null => false
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "grade_types", :force => true do |t|
    t.column "name",       :string,   :limit => 200, :default => "", :null => false
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "idea_attachments", :force => true do |t|
    t.column "idea_id",      :integer,                                 :null => false
    t.column "user_id",      :integer,                                 :null => false
    t.column "content_type", :string,   :limit => 128, :default => "", :null => false
    t.column "org_filename", :string,   :limit => 200, :default => "", :null => false
    t.column "size",         :integer,                                 :null => false
    t.column "created_at",   :datetime,                                :null => false
    t.column "updated_at",   :datetime,                                :null => false
    t.column "deleted_at",   :datetime
    t.column "file_data",    :binary
  end

  create_table "idea_categories", :force => true do |t|
    t.column "name",       :string,   :limit => 200, :default => "", :null => false
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "idea_comment_types", :force => true do |t|
    t.column "name",       :string,   :limit => 200, :default => "", :null => false
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "idea_comments", :force => true do |t|
    t.column "idea_id",              :integer,                  :null => false
    t.column "user_id",              :integer,                  :null => false
    t.column "comment",              :text,     :default => "", :null => false
    t.column "created_at",           :datetime,                 :null => false
    t.column "updated_at",           :datetime,                 :null => false
    t.column "deleted_at",           :datetime
    t.column "idea_comment_type_id", :integer,                  :null => false
  end

  create_table "idea_grades", :force => true do |t|
    t.column "idea_id",       :integer,  :null => false
    t.column "user_id",       :integer,  :null => false
    t.column "grade_type_id", :integer,  :null => false
    t.column "value",         :integer,  :null => false
    t.column "created_at",    :datetime, :null => false
    t.column "updated_at",    :datetime, :null => false
    t.column "deleted_at",    :datetime
  end

  create_table "ideas", :force => true do |t|
    t.column "user_id",          :integer,                                 :null => false
    t.column "idea_category_id", :integer,                                 :null => false
    t.column "title",            :string,   :limit => 200, :default => "", :null => false
    t.column "body",             :text,                    :default => "", :null => false
    t.column "created_at",       :datetime,                                :null => false
    t.column "updated_at",       :datetime,                                :null => false
    t.column "deleted_at",       :datetime
  end

  create_table "invite_users", :force => true do |t|
    t.column "email",        :string,   :limit => 256, :default => "", :null => false
    t.column "invite_code",  :string,   :limit => 32,  :default => "", :null => false
    t.column "from_user_id", :integer,                                 :null => false
    t.column "invite_at",    :datetime
    t.column "created_at",   :datetime,                                :null => false
    t.column "updated_at",   :datetime,                                :null => false
    t.column "deleted_at",   :datetime
  end

  create_table "meeting_agendas", :force => true do |t|
    t.column "meeting_id", :integer,                                  :null => false
    t.column "title",      :string,   :limit => 2000, :default => "", :null => false
    t.column "position",   :integer,                  :default => 1,  :null => false
    t.column "created_at", :datetime,                                 :null => false
    t.column "updated_at", :datetime,                                 :null => false
    t.column "deleted_at", :datetime
  end

  create_table "meeting_entry_users", :force => true do |t|
    t.column "meeting_id", :integer,  :null => false
    t.column "user_id",    :integer,  :null => false
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
    t.column "deleted_at", :datetime
  end

  create_table "meeting_log_types", :force => true do |t|
    t.column "name",       :string,   :limit => 200, :default => "", :null => false
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "meeting_logs", :force => true do |t|
    t.column "meeting_id",        :integer,                                  :null => false
    t.column "voice",             :string,   :limit => 2000, :default => "", :null => false
    t.column "voice_user_id",     :integer
    t.column "type_id",           :integer
    t.column "meeting_agenda_id", :integer,                                  :null => false
    t.column "created_at",        :datetime,                                 :null => false
    t.column "updated_at",        :datetime,                                 :null => false
    t.column "deleted_at",        :datetime
  end

  create_table "meetings", :force => true do |t|
    t.column "project_id",          :integer,                                  :null => false
    t.column "create_user_id",      :integer,                                  :null => false
    t.column "facilitator_user_id", :integer
    t.column "clerk_user_id",       :integer
    t.column "title",               :string,   :limit => 2000, :default => "", :null => false
    t.column "start_at",            :datetime
    t.column "created_at",          :datetime
    t.column "place_id",            :integer,                                  :null => false
    t.column "end_at",              :datetime,                                 :null => false
    t.column "updated_at",          :datetime,                                 :null => false
    t.column "deleted_at",          :datetime
    t.column "open_flag",           :boolean,                                  :null => false
    t.column "room_schedule_id",    :integer,                                  :null => false
  end

  create_table "milestones", :force => true do |t|
    t.column "name",        :string,   :limit => 200, :default => "", :null => false
    t.column "position",    :integer,                                 :null => false
    t.column "project_id",  :integer,                                 :null => false
    t.column "description", :string,   :limit => 500
    t.column "goal_at",     :datetime,                                :null => false
    t.column "deleted_at",  :datetime
    t.column "created_at",  :datetime,                                :null => false
    t.column "updated_at",  :datetime,                                :null => false
  end

  create_table "places", :force => true do |t|
    t.column "name",       :string,   :limit => 200, :default => "", :null => false
    t.column "delete_at",  :date
    t.column "occupancy",  :integer,                                 :null => false
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "project_attachments", :force => true do |t|
    t.column "project_id",   :integer,                                  :null => false
    t.column "user_id",      :integer,                                  :null => false
    t.column "content_type", :string,   :limit => 128,  :default => "", :null => false
    t.column "org_filename", :string,   :limit => 200,  :default => "", :null => false
    t.column "size",         :integer,                                  :null => false
    t.column "created_at",   :datetime,                                 :null => false
    t.column "updated_at",   :datetime,                                 :null => false
    t.column "deleted_at",   :datetime
    t.column "file_data",    :binary
    t.column "comment",      :string,   :limit => 2000
  end

  create_table "project_entry_guest_users", :force => true do |t|
    t.column "project_id",     :integer,  :null => false
    t.column "invite_user_id", :integer,  :null => false
    t.column "created_at",     :datetime, :null => false
    t.column "updated_at",     :datetime, :null => false
    t.column "deleted_at",     :datetime
  end

  create_table "project_entry_users", :force => true do |t|
    t.column "project_id", :integer,  :null => false
    t.column "user_id",    :integer,  :null => false
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
    t.column "deleted_at", :datetime
  end

  create_table "projects", :force => true do |t|
    t.column "name",       :string,   :limit => 200,  :default => "", :null => false
    t.column "summary",    :string,   :limit => 2000, :default => "", :null => false
    t.column "owner_id",   :integer,                                  :null => false
    t.column "start_at",   :datetime,                                 :null => false
    t.column "goal_at",    :datetime,                                 :null => false
    t.column "created_at", :datetime,                                 :null => false
    t.column "updated_at", :datetime,                                 :null => false
    t.column "deleted_at", :datetime
  end

  create_table "room_schedules", :force => true do |t|
    t.column "place_id",   :integer,  :null => false
    t.column "user_id",    :integer,  :null => false
    t.column "start_at",   :datetime, :null => false
    t.column "end_at",     :datetime, :null => false
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
    t.column "deleted_at", :datetime
  end

  create_table "schedule_entry_users", :force => true do |t|
    t.column "schedule_id", :integer,  :null => false
    t.column "user_id",     :integer,  :null => false
    t.column "created_at",  :datetime, :null => false
    t.column "updated_at",  :datetime, :null => false
    t.column "deleted_at",  :datetime
  end

  create_table "schedules", :force => true do |t|
    t.column "user_id",       :integer,                                  :null => false
    t.column "title",         :string,   :limit => 200,  :default => "", :null => false
    t.column "description",   :string,   :limit => 4000, :default => "", :null => false
    t.column "start_at",      :datetime,                                 :null => false
    t.column "end_at",        :datetime,                                 :null => false
    t.column "created_at",    :datetime,                                 :null => false
    t.column "updated_at",    :datetime,                                 :null => false
    t.column "deleted_at",    :datetime
    t.column "day_long_flag", :boolean,                                  :null => false
  end

  create_table "statuses", :force => true do |t|
    t.column "name",       :string,   :limit => 200, :default => "", :null => false
    t.column "created_at", :datetime,                                :null => false
    t.column "updated_at", :datetime,                                :null => false
    t.column "deleted_at", :datetime
  end

  create_table "task_logs", :force => true do |t|
    t.column "task_id",        :integer,                                  :null => false
    t.column "change_user_id", :integer,                                  :null => false
    t.column "message",        :string,   :limit => 4000, :default => "", :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime,                                 :null => false
    t.column "deleted_at",     :datetime
  end

  create_table "tasks", :force => true do |t|
    t.column "project_id",     :integer,                                  :null => false
    t.column "milestone_id",   :integer
    t.column "create_user_id", :integer,                                  :null => false
    t.column "treat_user_id",  :integer,                                  :null => false
    t.column "status_id",      :integer,                                  :null => false
    t.column "title",          :string,   :limit => 200,  :default => "", :null => false
    t.column "content",        :string,   :limit => 4000, :default => "", :null => false
    t.column "created_at",     :datetime
    t.column "goal_at",        :datetime,                                 :null => false
    t.column "complete_at",    :datetime
    t.column "updated_at",     :datetime,                                 :null => false
    t.column "deleted_at",     :datetime
  end

  create_table "users", :force => true do |t|
    t.column "office_id",                 :string,   :limit => 100, :default => ""
    t.column "email",                     :string,   :limit => 256, :default => "", :null => false
    t.column "created_at",                :datetime,                                :null => false
    t.column "updated_at",                :datetime,                                :null => false
    t.column "im",                        :string,   :limit => 256
    t.column "log_input_type",            :integer,                                 :null => false
    t.column "name",                      :string,   :limit => 200, :default => "", :null => false
    t.column "password",                  :string,   :limit => 32,  :default => "", :null => false
    t.column "deleted_at",                :datetime
    t.column "login",                     :string,                  :default => "", :null => false
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

  create_table "users_divisions", :force => true do |t|
    t.column "user_id",     :integer,  :null => false
    t.column "division_id", :integer,  :null => false
    t.column "created_at",  :datetime, :null => false
    t.column "updated_at",  :datetime, :null => false
    t.column "deleted_at",  :datetime
  end

  create_table "wikis", :force => true do |t|
    t.column "project_id",     :integer,                                  :null => false
    t.column "create_user_id", :integer,                                  :null => false
    t.column "title",          :string,   :limit => 200,  :default => "", :null => false
    t.column "body",           :string,   :limit => 4000, :default => "", :null => false
    t.column "created_at",     :datetime
    t.column "update_at",      :datetime,                                 :null => false
    t.column "deleted_at",     :datetime
  end

end
